# Generated by Django 3.0.8 on 2021-06-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_test_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='test_create',
            name='test_name',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='test_create',
            name='test_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.test_code'),
            preserve_default=False,
        ),
    ]
