# Generated by Django 3.0.8 on 2021-06-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210616_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_code',
            new_name='test_info',
        ),
    ]
