# Generated by Django 3.0.8 on 2021-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210616_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_create',
            name='test_code',
            field=models.IntegerField(),
        ),
    ]
