# Generated by Django 3.0.8 on 2021-06-16 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0005_auto_20210616_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_info',
        ),
        migrations.AlterField(
            model_name='test_create',
            name='test_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
